---
title: "smpl_yr_181001"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# setwd("D:/Shared/BackedUp//Caitlin/RecruitmentReview")
# setwd("//goshawk.sefs.uw.edu/Space_Lawler/Shared/BackedUp/Caitlin/RecruitmentReview")

# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("RColorBrewer")

library(tidyverse)
library(dplyr)
library(RColorBrewer)
display.brewer.pal(7, "Set1")
palette <- brewer.pal(7, "Set1")



# Load database, setting blank strings to NA (n.b., some blanks still persist...)
# data <- read.csv("smpl_yrs.csv", header = TRUE) # now retired
# data <- read.csv("smpl_yrs_181124.csv", header = TRUE) # has tighter filter re: mgmt
# data <- na.omit(data)

# data <- read.csv("rubric_simple.csv", header = TRUE) # no kemp
# data <- read.csv("rubric_simple_190406.csv", header = TRUE)
# w/ kemp 2016, on avg; duplicated for kemp 2019 -- same fires
# w/ haffey 2018
# w/ davis assuming sampled 2016, from tbl in SI (first pub 190311)
# w/ young et al. 2019
data <- read.csv("rubric_simple_190619.csv", header = TRUE)
# Includes all in mendeley folder called 190305 (plus Kim's paper that came out a week later on March 11th)
# data <- na.omit(data)

```

```{r setup, include=FALSE}

# hist(data$btwn.yr, 10)
# 
# g <- ggplot(data, aes(x=btwn.yr))
# g + geom_histogram(breaks = seq(0,46, by = 2), color = "white", fill = "black") + 
#   # coord_flip() +
#   theme_classic() + 
#   theme(text = element_text(color = "black", size = 12), # sets all text elements
#         # legend.position = ("none"),
#         axis.ticks.x = element_blank(),
#         axis.ticks.y = element_blank()) +
#   scale_x_continuous(expand = c(0,0)) + 
#   scale_y_continuous(expand = c(0,0), lim = c(0,35)) +
#   labs(x = "Years between fire and sampling",
#        y = "Number of sampling efforts", color = "black", size = 16)
# 
# ggsave("hist_samp_yrs.png", width = 5, height = 3)

data <- data %>%
  dplyr::select(yrs.btwn)

# single color
g <- ggplot(data, aes(x=yrs.btwn, fill = palette[4]))
# p <- g + geom_histogram(breaks = seq(0,45, by = 1), color = "white") +
# p <- g + geom_histogram(bins=45) +
p <- g + geom_histogram(binwidth = 1, color = "white") +
  theme_bw(base_size = 18) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        text = element_text(color = "black", size = 16), # sets all text elements
        legend.position = ("none"),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank()) +
  # scale_x_continuous(expand = c(0,0)) +
  scale_x_continuous(breaks = (seq(0, 45, by = 5)), expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0), lim = c(0,50)) +
  coord_cartesian(ylim = c(0,50)) +
  scale_fill_manual(values = palette[4]) +
  labs(x = "Years between fire and sampling",
       y = "Number of sampling efforts", color = "black", size = 16) +
  geom_vline(xintercept = median(data$yrs.btwn),
             lty = 2, lwd = 0.5, col = "red") #+
  # annotate("text", x = 12.5, y = 28, label = "median", size = 6)
p

mean(data$yrs.btwn)
median(data$yrs.btwn)

dev.off()
tiff("SampYrHist1col_400dpi_190619.tiff", width = 600, height = 250, units = "px")
p
dev.off()
# ggsave("SampYrHist1col_400dpi_190406.tiff", width = 5, height = 3, dpi = 400)



# two colors
my.col <- c("#009933", "#330066")

g <- ggplot(data, aes(x=yrs.btwn, fill=record.successive.samp))
g + geom_histogram(breaks = seq(0,46, by = 1), color = "white") +
  # coord_flip() +
  theme_classic() +
  theme(text = element_text(color = "black", size = 12), # sets all text elements
        legend.position = ("none"),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank()) +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0), lim = c(0,25)) +
  scale_fill_manual(values = rev(my.col)) +
  labs(x = "Years between fire and sampling",
       y = "Number of sampling efforts", color = "black", size = 16)

ggsave("SampYrHist2col_400dpi_181110.tiff", width = 5, height = 3, dpi = 400)


```
